### PR TITLE
Format the design group

### PR DESCRIPTION
**Pull request by MariusVolkhart**
Format the descriptions in the design group

### CODE REVIEW

**Comment by fabdrol** [comment]
Makes sense to me, @SignalK/contributors any objections to merging?

**Comment by MariusVolkhart** [comment]
One question on this one. The `draft` object uses centimeters as the unit. Should this be converted to meters for SI compliance?

**Comment by timmathews** [comment]
Yeah, meters would be better

**Comment by tkurki** [comment]
@MariusVolkhart are you going to take care of the `draft` change as part of this PR?

**Comment by MariusVolkhart** [comment]
@tkurki yes will take care of it tonight. Sorry for the delay

**Comment by fabdrol** [comment]
Looks good, I'll proceed and merge.

**Pull request merged**
