### PR TITLE
Fix schema files to be valid against http://json-schema.org/draft-04/schema#

### PR DESCRIPTION
**Pull request by bkp7**
Fixed Schemas so that they validate. It seems the schemas themselves are not included in the tests.

Also I discovered that the uuid could be set to anything at all because the additionalProperties had not been set to false, so I've fixed that too.

### CODE REVIEW

**Comment by tkurki** [comment]
Great stuff! I am all for merging this, just one question: did you manually validate all these? It would be great to add automatic tests so that everything does not degrade over time as things evolve. The lack of runnable tests is imho the root cause for these issues.

If you did this manually it would be great to share command line instructions in the readme.

**Comment by bkp7** [comment]
They were validated using Altova. 

I will be working through a number of other issues we have found with the schemas over the next couple of days (on different branches), but I suggest you leave this here and I will aim to add the tests in.. 

Any objection to adding in tests for the samples so they stay relevant?

Also, is there any reason the tests are not all valid SignalK json? Some are snipets. I would have found it a lot easier if all the tests validated against one of the top level schemas which I think are: signalk.json, delta.json, subscribe.json, unsubscribe.json and discovery.json. If that's correct I think it should be in the documentation.

**Comment by tkurki** [comment]
See also
https://github.com/SignalK/specification/tree/ajv-validator
https://github.com/SignalK/specification/issues/246

It would be absolutely wonderful to add validation of the samples to the tests.

The samples and tests have grown over time and are frankly a mess. You may consider also removing some of the samples or replacing them with better ones.

Another point to consider is that the samples used in the documentation under `gitbook-docs` would be separate files, included in the documentation, so that we can have validation tests for them as well. Even if what's needed in the documentation is a snippet we can add a test that validates it with some scaffolding.

Are you sure you want to keep this open? I would rather merge this and continue off master.

**Comment by bkp7** [comment]
OK, merge this and I'll look at adding tests for the schemas later

**Pull request merged**
