### PR TITLE
Added SAR aircraft, updates tests to handle aircraft, add vessel.mmsi…

### PR DESCRIPTION
**Pull request by rob42**
… check

See #337

### CODE REVIEW

**Comment by rob42** [comment]
Added aton as well.

**Comment by rob42** [comment]
aton commit includes fix to design.json to use commonValues rather that source/timestamp

**Comment by rob42** [comment]
The model I have used for these additions is to create a new root branch (eg aton) and duplicate the current tree we have for vessels, trimming the obviously useless bits like `sails` :-)
This means the same structure exists across all root object `vessels`, `aton`, `aircraft` and `sar` so there is minimal complexity in working with them if you already know `vessels`.

Remaining category is AIS coastal stations and AIS groups...

**Comment by sbender9** [comment]
I don't see aton type anywhere?

**Comment by sbender9** [comment]
Also aton name?

**Comment by sbender9** [comment]
I do get a name for AtoN's from AIS.  On the chesapeake there are sometimes location/direction related: SC (South Center?), NE, SW, etc. Sometime's it's the buoy? number.

**Pull request merged**
