### PR TITLE
Standard js api to look up metadata for a key

### PR DESCRIPTION
**Pull request by tkurki**
@sumps brought up the need for a standard (js) api to look up metadata, such as units and description and example, about a key.

This PR adds one with JavaScript implementation. I think this should be exported in https://github.com/SignalK/signalk-js-client/ but the implementation is really schema dependent so should live close to it.

TODO
- [x] support for foo.*.bar keys
- [ ] ~~proper implementation based on schema files, not on the generated keyswithmetadata.json~~
- [ ] documentation (in signalk-js-client ?)

### CODE REVIEW

**Comment by tkurki** [comment]
I realised that if we produce a keyswithmetadata.json for people to use as such and as the fodder for `getMetadata` implementation the same data would work pretty well as schema keys documentation, including descriptions, units and examples.

I am not sure if it is a great idea to use hand crafted logic like in this PR to pull the information out of the schema files, but I don't see a viable alternative. Both @rob42's keys listing in java and @fabdrol's efforts do essentially the same, figure out a way to extract a selection of stuff from the schema files.

Anyway, take a look at doc.md in this PR or run `npm run build` to generate it for yourself.

The file does not have the intermediate levels but nor does it [have too much information going through your head](https://open.spotify.com/track/34duNcSyV9qP1Q0kEYn2C9).

The .md idea I credit to @rob42.

So essentially this is a step towards #46.

**Comment by sailoog** [comment]
Really useful. I miss defined values in doc.md. 
ex. 
design.keel.type: "enum": [
      "long",
      "fin",
      "flare",
      "bulb",
      "wing",
      "centerboard",
      "kanting",
      "lifting",
      "daggerboard"
]

**Comment by tkurki** [comment]
- [ ] enums to doc

**Comment by rob42** [comment]
You missed the best of all `foiling` :-)

**Comment by tkurki** [comment]
Depends on #290.

**Comment by tkurki** [comment]
@sailoog enums have been in the doc for some while now: http://signalk.org/specification/master/keys/#vesselsregexpdesignkeeltype

**Comment by tkurki** [comment]
Superceded by #332

**Pull request closed without merging**
