### PR TITLE
Add server information to discovery

### PR DESCRIPTION
**Pull request by sbender9**
Add details like name, version and capabilities to the discovery information.

### CODE REVIEW

**Comment by sbender9** [comment]
Should we make capabilities an enum or leave it open?

**Comment by sbender9** [comment]
I changed to an enum an started with values from @timmathews comment on slack:

```
"serverCapabilityEnum": {
      "enum": [
        "stream",
        "subscription",
        "auth",
        "meta",
        "ratelimit",
        "command"
      ]
    },
```

**Comment by tkurki** [comment]
I think that `id` and `version` would be ready to merge, as they are pretty well defined server metadata, but `capabilities` is far from ready to merge. Maybe split that off to a separate PR?

**Comment by sbender9** [comment]
Agreed

**Comment by tkurki** [comment]
Could you please update the PR? I think that the server information is ready to be added, just remove the capabilities.

**Comment by sbender9** [comment]
Re-creating because I deleted my branch...

**Pull request closed without merging**
