### PR TITLE
Message schemas

### PR DESCRIPTION
**Pull request by rob42**
Added meta and _attr  objects to definitions.json
Created messages dir, and added subscribe and unsubscribe schemas

### CODE REVIEW

**Comment by tkurki** [comment]
@rob42 how about some examples & tests that validate those? We can cooperate, you provide the examples and I can add the tests.

**Comment by rob42** [comment]
samples are added, not sure how you run the tests?

**Comment by tkurki** [comment]
I'll create the tests, but attr and meta would need real usage examples, since they are meant to be used in context, right?

**Comment by rob42** [comment]
Added https://github.com/SignalK/specification/blob/messageSchemas/samples/signalk-depth-meta-attr.json

**Comment by tkurki** [comment]
Sorry about the extra commits, just 5baad1c7418b0a20119d13a14bf2eae0cd660713 is relevant.

**Comment by fabdrol** [comment]
@rob42 should this be merged?

**Comment by rob42** [comment]
Yes, @tkurki - can you pls look at the tests, seems to fail on environment/depth/belowKeel/source (not) being an object - which should be ok i think.
Then pls merge.

**Comment by fabdrol** [comment]
@rob42 @tkurki I'll have a look at the tests, push some fixes and merge when checks pass.

**Comment by fabdrol** [comment]
@rob42 @tkurki I changed the definitions file and to make the tests pass. Could you check if everything is still as intended?

**Comment by rob42** [comment]
I think this is ok now. I put a description of alarms handling in the wiki too. This is how the signalk-jacva-server does it at present

**Comment by fabdrol** [comment]
Okay, then I'll merge. We can review master after all merges have been processed.

**Pull request merged**
