### PR TITLE
[WIP] RFC 0004: Entertainment Group

### PR DESCRIPTION
**Pull request by timmathews**
This PR corresponds to issue #293 (RFC 0004: Entertainment).

### CODE REVIEW

**Comment by fabdrol** [comment]
@timmathews is this stale/dead?

**Comment by fabdrol** [comment]
@timmathews as per the discussion in #core, please let me know if you intent to continue work on this. If not, I'll close it for lack of activity. 

@bkp7 I don't disagree, but it's doing nobody any good to have PRs "linger" for this long. The PR needs work anyway, to make it work with the current master, and possibly documentation, samples, tests, etc (especially since this concerns an entirely new group). If the solution is still valid, it can be retrieved easily and re-submitted in a more comprehensive and working PR.

**Comment by bkp7** [comment]
@fabdrol, agreed re lingering PR's

**Comment by fabdrol** [comment]
@timmathews I'm closing this for inactivity. Please re-submit a PR if you get around to this again!

**Pull request closed without merging**
