### PR TITLE
Rework electrical dc: batteries

### PR DESCRIPTION
**Pull request by tkurki**
DC schema had a bunch of reference & structural errors and could not handle more than one battery.

This pull request fixes batteries, but inverter part still needs work.

Test includes a sample document with multiple batteries.

### CODE REVIEW

**Comment by sumps** [comment]
You are making good progress with DC but if we are going to have lots of manual settings, which I think is correct, I think it is really important that we include these in a separate section of the scheme so that they can be saved, shared and published for other owners of similar boats to use, as mentioned in issue #86

**Comment by sumps** [comment]
We have....
- Alarm values
- Visualisation properties i.e. Max RPM
- Equipment information
- etc.
In the data objects and I am not sure this is the best way.

**Comment by timmathews** [comment]
@sumps, keep in mind that a lot (most?) of the schema objects are optional, so there is no hard requirement to support them.

I think it makes sense to keep all of this descriptive data in the object it describes (however, it probably(?) belongs in the `_meta` sub-object). So instead of:

```json
"batteries": {
  "house1": {
    "name": "House battery 1 (forward)",
    "location": "Under forward bunk",
    "manufacturerName": "MasterVolt",
    "manufacturerModel": "AGM 12/130",
    "chemistry": "FLA",
    "mode": {
      "value": "discharging"
    },
    "temperature": {
      "value": 290
    },
    "voltage": {
      "value": 12.5,
      "nominal": 12
    },
    "current": {
      "value": 0.1
    }
  }
}
```
perhaps
```json
"batteries": {
  "house1": {
    "mode": {
      "value": "discharging"
    },
    "temperature": {
      "value": 290
    },
    "voltage": {
      "value": 12.5,
      "_meta": {
        "nominal": 12,
        "minimum": 10,
        "maximum": 15
      }
    },
    "current": {
      "value": 0.1
    },
    "_meta": {
      "name": "House battery 1 (forward)",
      "shortName": "HB1",
      "location": "Under forward bunk",
      "manufacturerName": "MasterVolt",
      "manufacturerModel": "AGM 12/130",
      "chemistry": "FLA"
    }
  }
}
```

**Comment by sumps** [comment]
@timmathews by putting this data in _meta sub-object, does this give us a way to get all of the _meta data with a restAPI call ? I am thinking of a way to efficiently extract this _meta data if we want to export it and share it and also to import it. This way if I have just bought a new boat and want to upload the _meta data for a similar/identical boat, there is an easy way to do it.

**Comment by tkurki** [comment]
If all _meta is needed we can define an api route for retrieving that information. Just putting them in _meta doesn't add any additional functionality.

I don't see the whole _self_ json growing big enough to be unwieldy, one can also retrieve that and extract all _meta properties.

**Comment by tkurki** [comment]
- [ ] move static information under _meta

**Comment by rob42** [comment]
The idea behind the `_name` is that a server will strip out all `_*` names from the tree on normal transmission. Just a convenient way to easily mark a sub-tree as 'dont send'. But as @tkurki says, we just add a flag or request param `&meta=true` to get meta sent out too.

**Comment by rob42** [comment]
Just looking over this, maybe these alarm and warning values for `vessels.*.electrical.dc.definitions.dcSource.current.measured"` belong in `.meta`?  If they are defined as zones they can be handled by the std alarms functionality.
```
vessels.*.electrical.dc.definitions.dcSource.current.faultLower";
vessels.*.electrical.dc.definitions.dcSource.current.faultUpper";
vessels.*.electrical.dc.definitions.dcSource.current.warnLower";
vessels.*.electrical.dc.definitions.dcSource.current.warnUpper";
```

**Comment by sumps** [comment]
@rob42 what is the Std Alarm functionality ? I have read the Alarm section in the SignalK.org>Developers>Metadata but is there more info anywhere ? It looks to me that the Alarm method has been focused on a consumer being able to check a data value and see if an alarm should be triggered. There does not seem to be any consideration for NMEA alarms/alerts, which should be handled by Signal K.
Alarms needs to be given serious consideration or removed from the V1 spec. Maybe I have mis-understood something, but at the moment, it looks like we have alarms in the spec as a place holder but no clear mechanism for handling them.

**Comment by rob42** [comment]
@sumps in this case (eg relative to dc power) it is a matter of compare and raise alarm. But your point re NMEA alarms is valid too. Jumping to  #96 for that one

**Comment by fabdrol** [comment]
Shouldn't the definitions be moved to definitions.json?

**Comment by tkurki** [comment]
@rob42 in schema (master + this branch) meta is without the underscore - the fix should be a separate issue.

**Comment by tkurki** [comment]
@fabdrol If the definitions are only used in electrical_dc I want to keep this schema self-contained and not extract definitions to a separate file.

**Comment by tkurki** [comment]
As the batteries part is done and the master version is unusable I think we should merge this asap.

**Comment by tkurki** [comment]
Warnings and errors are for now just simple values, not zones.

**Pull request merged**
