### PR TITLE
Object valued properties under value in full model

### PR DESCRIPTION
**Pull request by tkurki**
This PR is work in progress to treat object valued properties the same as scalar values: the object under `value` property, with `timestamp`, `$source` and `values` siblings.

TODO:
- [x] position first pass
- [x] values handling
- [x] Check other object valued properties
- [x] Generate proper keys documentation and keyswithmetadata.json

### CODE REVIEW

**Comment by tkurki** [comment]
First problem caught by tests: how do you pass the name of an AIS target, since `name` is vessel object's  property, without `value`.

**Comment by rob42** [comment]
First, we should define a list of reserved words for keys like `value, timestamp, $source, source,` etc. That will avoid awkward objects in future. 

In the case above I think we need to be explicit about the difference between branch and leaf, and the ability of a branch to have arbitrary properties, whereas a leaf can have ONLY `value, timestamp, etc`.

Otherwise it seems to me we will soon have a very complex recursive `value.object.path.value.object.value` chain.

**Comment by tkurki** [comment]
@rob42 I didn't quite get your comment _In the case above_.  

So what to do about the `name` in incoming AIS targets? Do not send deltas about them at all, just in the full model? Node server uses deltas for all communication from the producers, so some solution needs to be there for the names to end up in the full model.

The reserved property names should be documented, but the issue is not very pressing, because schema changes should go via PRs anyway (unless we fumble).

**Comment by rob42** [comment]
Oh, I see your problem! 

This is the code Ive used to decode deltas sent to the browser
```javascript
 ais.values.forEach(function(value) {
	//console.log(value);
	if(value.path === 'navigation.position.latitude'){
		//console.log(value.value);
		lat=value.value;
	}
	if(value.path === 'navigation.position.longitude'){
		//console.log(value.value);
		lon=value.value;
	}
	if (value.path === 'navigation.position') {
                   //console.log('Pos:'+value.value.latitude+':'+value.value.longitude);
                    lat = value.value.latitude;
                    lon = value.value.longitude;
            }
	if(value.path === 'navigation.courseOverGroundTrue'){
		cog=value.value;
		radians = value.value-(Math.PI*.5);//util.toRad(value.value-90);
	}
	if(value.path === 'navigation.speedOverGround'){
		sog = value.value;
	}
	if(value.path === 'mmsi'){
		mmsi = value.value;
	}
	if(value.path === 'flag'){
		flag = value.value;
	}
	if(value.path === 'port'){
		port = value.value;
	}
	if(value.path === 'name'){
		name = value.value;
	}
	if(value.path === 'communication.callsignVhf'){
		vhf = value.value;
	}
	if(value.path === 'navigation.state'){
		state = value.value;
	}
});
```
You can see I send `name` as a `path`, and `value` as the value.
Seems to work.
Rob

**Comment by tkurki** [comment]
`name` is just an example - the same goes for for example `mmsi` and any other simple property, that does not require the value/values/$source/timestamp handling. 

Either we start sprinkling schema awareness to the part of app that creates the full model based on incoming deltas or figure out a way to specify such property updates in delta so that they can be handled generically.

I think making delta => full mapping schema aware is a bad idea in several ways. It does not allow one to use emerging properties, that have not yet made it to the schema, and makes the implementation a lot more complex.

Mulling this over I have come to like the idea of extending the `delta` format to cover this case.
For example like this:
```
{
  "updates": [{
    "context": "vessels.urn:mrn:imo:mmsi:236333000",
    "source": {...},
    "timestamp": "2014-08-15T19:06:44.137",
    "properties": [{
      "path": "name",
      "value": "HOOGE"
    },{
      "path": "mmsi",
      "value": "236333000"
    }]
  }]
}
```

This would clearly distinguish the simple properties from the more elaborately handled values. It would also be pretty backwards compatible, as we are adding a property to the delta's updates property.

Thoughts?

**Comment by rob42** [comment]
Hmm, works - but are there security implications..I guess no worse than now as we dont record the source/timestamp for these properties anyway. And we do have the source and timestamp of the delta.

At a meta level we have created two types of leaf (value), those that have source/timestamp, and those that dont... maybe we need to fix that instead?

**Comment by tkurki** [comment]
Yes on two leaf types - except that they've been there all along. 

What did you mean by _fix that instead_?

**Comment by rob42** [comment]
maybe we should convert all the 'properties' to  values

That would simplify the processing and mean all leaf values are the same

**Comment by rob42** [comment]
Just had a quick look, there are a lot of places where 'properties ' are used, See resources, json
Not practical or useful to convert them all.

**Comment by joabakk** [comment]
I tend to agree with @rob42 on this one. Having tried to process environment.current in the same way as other paths, it does not lend itself as easily to automation, ref instrumentpanel etc. There may be workarounds I'm not familiar with, but it is easier to look for the value property

**Comment by tkurki** [comment]
@joabakk are you talking about using environment.current streamed as delta or via rest as full?

**Comment by joabakk** [comment]
Not really sure what I'm doing @tkurki ... For most measured values, I can get the value by adding .value to the path for say plugin `_.get(app.signalk.self, path)`, but not for the special cases like environment.current

**Comment by bkp7** [comment]
Has a resolution for the above been agreed?

Looks to me like 2 issues in the above:

@joabakk raised the example of environment.current. It seems to me this just needs to be corrected in the schema. IMHO these values should have the full complex value, see in the example below the difference between current and wind we have at the moment which makes no sense to me. Why should wind.directionTrue have meta data and current.setTrue not? To my mind the meta data on these values is really important to allow the gauges and displays to work automatically.

 ```json
{
  "vessels": {
    "urn:mrn:imo:mmsi:230099999": {
      "mmsi": "230099999",
      "environment": {
        "current": {
          "drift": 3.12,
          "setTrue": 1.5,
          "timestamp": "2014-08-15T19:00:15.402Z",
          "$source": "foo.bar"
        },
        "wind": {
          "directionTrue": {
            "value": 1.8,
            "meta": {},
            "timestamp": "2014-08-15T19:00:15.402Z",
            "$source": "foo.bar"
          },
          "speedOverGround":{
            "value": 5.24,
            "meta": {},
            "timestamp": "2014-08-15T19:00:15.402Z",
            "$source": "foo.bar"
          }
        }
      }
    }
  },
  "version": "1.0.0"
}
```

I propose a new issue to go through the schema and check for/correct any cases like current. 

The second issue is the many other properties as identified by @rob42 and @tkurki which should not have, and don't need the full complex value. @tkurki has proposed 1 solution which looks like it should work. I can think of an alternative which is to explicitly include the .value for the complex cases:
```json
{
  "context": "vessels.urn:mrn:imo:mmsi:236333000",
    "source": {...},
    "timestamp": "2014-08-15T19:06:44.137",
    "updates": [
    {
      "values": [
        {
          "path": "mmsi",
          "value": "212345678"
        },
        {
          "path": "environment.wind.directionTrue.value",
          "value": 5.5
        }
      ]
    }
  ]
}
```
Not backwardly compatible, but has the advantage of additional flexibility because anything can be updated with the delta message. eg. changing the red warning zone on a tacho when engine goes into limp home mode.

Just some thoughts to try and move this along....

**Comment by tkurki** [comment]
Current is actually like that per design, see #41. If we go through with this PR current properties should be pushed one level down, under `value`.

So whenever a property is fundamentally composite or it doesn't make sense in this day and age to handle the parts discretely it is object valued. 

Whether or not something is composite property or just a couple of discrete properties is another discussion - this PR deals with the mechanisms to represent them.

**Comment by tkurki** [comment]
Thanks for the fresh thinking on appending `.value` to most paths. 

I am not overly fond of it, because it makes the most prevalent cases more verbose.

**Comment by bkp7** [comment]
OK. Thanks for pointing out #41, I had not read that and it makes sense of the rationale behind other values which are not composite (Attitude, Keel, ...). IMHO that logic is flawed though, with gauge info now being stored in the metadata with each value. I have opened issue #329 to separate it from this one.

**Comment by bkp7** [comment]
I tend to agree with your verbose point, however against that, having 2 separate sections 'properties' and 'values' adds some complication. In reality I think either approach will work, and presumably if your properties approach is taken any value could be set in there, including a composite value?

If so, you could argue that your properties section is essentially the same as what I proposed, and the values section offers a less verbose way to send the more frequently updated values that most instruments will be interested in.

Also, regarding the verbose point, in many cases there will be a lot more verbage caused by the issue I raised in #275. We are currently developing a native Signal K sensor suite, and due to the design it is not practical to read all the sensors at exactly the same time so our system will be producing verbose deltas in the format you suggested in #275 anyway.

Having said all the above, what seems to me to be important is to make a decision on this.

**Comment by tkurki** [comment]
Yes on allowing composite values for properties.

About timestamps and verbosity: would you not want to send the data as soon as you read it from the sensor, so you would be sending out deltas for every reading anyway.

**Comment by bkp7** [comment]
Some sensors are being read up to several hundred times per second and digitally smoothed to reduce noise. Others have a slower read rate so are read periodically 1-5 times per second say. This is done on a round robin basis so not all sensors are read at the same time.

Since there can be many subscribers to any given sensor, and each can have requested different update rates there is no link between the actual sensor reading and sending of the data. So the methodology is that when the time comes to send more data to a particular subscriber, the latest available data for each sensor is collected up and sent to the websockets queue.

We have also found that each websocket push has an overhead and if we send each measurement separately we have to deal with complex caching and queue management at the websockets layer.

So we have taken the view that if a subscriber asks for several items on the same refresh period we supply them all together in one delta message.

We have considered rounding the times against each sensor reading eg. to the nearest 0.2s and then treating that as the timestamp for all the sensor readings. The only problem with that is if the upstream consumer is trying to use the data other than for display. eg. to calculate rate of change from the raw data, this will then make any such derivation less accurate because the timings are off.

**Comment by rob42** [comment]
This is drifting into the too hard list:-)
The language below is specific, `value` is the signalk sibling for `timestamp`, value is the stored data. Hopefully avoids the ambiguity of talking about 3.451 being the the value of `value`....
 
Just trying to think laterally and back to the core issue, we have 4 types of path:
1) a path that has at least one child path that is an object. example = `..navigation`
2) a path with a child `value`, or `values`. Value will be a primitive, or simple array. example: `..navigation.courseOverGroundTrue`
3) A path not ending in `value`, no children, and with a primitive value. Example `mmsi`, @tkurki 's _properties_ above
4) A path with children, including  `source` and/or `timestamp` Example `..navigation.position.* This is a composite object.

So in delta format:
1) and 2) above are the usual case in signalk. 
4) Send a delta with `source` and/or `timestamp` where `value` is an object.

3) Is harder to identify in a delta. Maybe send a separate delta, in `updates`  send `values` without `source` and `timestamp`. Or we need a sibling to `updates`, but not `properties` as that will be jsoschema hell.

**Comment by rob42** [comment]
Case 2 above, easy to recognise composite values in delta:
```
{
    "context": "vessels.urn:mrn:imo:mmsi:234567890",
    "updates": [{
        "source": {
           ....
        },
        "timestamp": "2010-01-07T07:18:44Z",
        "values": [{
            "path": "navigation.position",
            "value": {
								"longitude": 173.1693,
								"latitude": -41.156426,
								"altitude": 0
								}
        }]
    }]
}
```

**Comment by rob42** [comment]
Case 3 above works well in delta like this:
```
{
    "context": "vessels.urn:mrn:imo:mmsi:234567890",
    "updates": [{
        "values": [{
            "attribute": "mmsi",
            "value": "234567890"
        }]
    }]
}
```
In the full tree it can be recognised as per my rule 3 above. 

Does that solve the issue in all scenarios? Except for the addition of `attribute` to the delta its backwards compatible too.

**Comment by tkurki** [comment]
Good analysis and solution, @rob42. I like the direction this is going. I will revisit the implementation.

**Comment by tkurki** [comment]
Does anybody have a good idea on how to find any object valued properties we are using? Can't recall anything but `position` and `current`.

**Comment by joabakk** [comment]
There is closestApproach from #366 if that is ok

**Comment by tkurki** [comment]
Hmmm, I came up with a way to shortcut the delta-to-properties-with-no-metadata problem with the following rule: _if a delta pathvalue has empty string as the path then merge the value's structure into the full model (without source & timestamp & value/values handling)_. This allows a delta like 

```
{
  "context": "vessels.urn:mrn:imo:mmsi:276810000",
  "updates": [
    {
      "source": {...},
      "timestamp": "2014-08-15T19:02:31.507Z",
      "values": [
        {
          "path": "",
          "value": {
            "name": "WRANGO"
          }
        }
      ]
    }
  ]
}
```
to set `name` property under a vessel's root. 

Thoughts? To me this looks like a very tidy solution to _"properties"_.

**Comment by tkurki** [comment]
Finally, I'm ready to merge this, bringing finally balance to the full model!

**Comment by tkurki** [comment]
- [ ] attitude

**Comment by tkurki** [comment]
This affects notifications as well: they are object valued and must go under `value` as well, if we are to be consistent.

- [ ] notifications

**Comment by tkurki** [comment]
Notifications done, (again) not aware of any more work to be done. N2k-signalk changes done. Nmea0183 parser new version did not have any validity tests, added some to obvious object valued properties and fixed any issues there.

**Comment by tkurki** [comment]
@sbender9 continue here, not really n2k-signalk specific
>Now we also don't get meta for things like design.beam. Not sure if that is handled by another change? Or is even possible now?

With the current master:
http://node-master.signalk.org/signalk/v1/api/vessels/self/design/beam/meta
```
{
units: "m",
description: "Beam length"
}
```
http://node-master.signalk.org/signalk/v1/api/vessels/self/design/beam
`Cannot GET /signalk/v1/api/vessels/self/design/beam`

So we do have meta for units & description available with direct HTTP call, even if there is no value there.

`design.beam` is actually a normal value with the metadata and `value/values`.

Digging into the schema a bit deeper still: design has some object valued fields, that should be pushed under `value` and some that are normal `numberValue`s.

- [ ] design.length
- [ ] design.keel

**Comment by sbender9** [comment]
I don't think any of those design fields should be normal numberValues.  They can actually come from multiple sources.

**Comment by tkurki** [comment]
Can or can not?

If multiple sources then they need to be numberValues.

**Comment by sbender9** [comment]
Sorry, brain fart. They CAN have multiple sources. And SHOULD be numberValues. `design.beam` for example.

**Comment by tkurki** [comment]
- [ ] undo dist addition before merging

**Comment by tkurki** [comment]
The design section is not quite so clear as to how ti should be fixed. Merging object valued properties, as there is considerable value in harmonising this for for example position in the full model.

**Pull request merged**
