### PR TITLE
Add opposite layline, reorganize layline, typo

### PR DESCRIPTION
**Pull request by joabakk**

### CODE REVIEW

**Comment by fabdrol** [comment]
@joabakk from looking at the changes, it looks good to me, except for the merge conflict. Could you look into that and solve it? 

Could you also include a short description on the context/motivation for this PR (i.e. an issue #, or the use case(s) and why the "old" specification wasn't up to scratch)?

**Comment by joabakk** [comment]
Thank you for looking into this. I have created issue #467 to expand the rationale and the conflict should be solved

**Comment by fabdrol** [comment]
Alright, looks good to me and Travis looks happy too. I'm okay to merge, if you are too @joabakk.

**Comment by joabakk** [comment]
Happy happy

**Pull request merged**
