### PR TITLE
Update multiple values documentation

### PR DESCRIPTION
**Pull request by tkurki**
The doc is outdated and doesn't match the schema nor the specified logic related to having multiple values in the full model, linked to sources.

TODO:
- [x]  replace temperetures with device oriented examples
- [ ] rewrite with `values` structure
- [ ] add `sources` handling

### CODE REVIEW

**Comment by tkurki** [comment]
Ping @rob42 @thomasonw

**Comment by thomasonw** [comment]
@tkurki - nice addition.  Question:  In the overall vision for Signal-K is there an intention at some time to do value-add processing?   Examples might include:

1. Qualifying of multiple position (lat/long) data values, selecting the 'preferred' one to commonly pass on to all apps requesting 'position'.  (Still allowing for a way to access data from all sources)
2. Monitoring of data values vs. limit values, proactively invoking an 'alarm' process of some type?

Just wondering.  Many value-add processes I think can live well at the app level (ala, example 2 above), but some seems like being the man-on-the-middle would be useful for a few (example 1 above).

**Comment by tkurki** [comment]
See https://github.com/SignalK/signalk-server-node/pull/105 for a plugin mechanism for server side value-add processing.

**Comment by thomasonw** [comment]
@tkurki Very nice!

**Comment by rob42** [comment]
@thomasonw - Every key can have a `meta` tag which includes ranges and alarms that apply to them. The server raises alarms by monitoring the value against the range and placing an entry in the `notifications` structure. See http://signalk.org/specification/master/data_model_metadata.html

In the java server background processes are used to derive true/apparent wind, periodically calculate magnetic deviation, anchor watch, etc.

**Comment by thomasonw** [comment]
You know, I will apologize for my lack of knowledge of what is already in SignalK - do appreciate the patience to 'educate me'!

**Comment by tkurki** [comment]
Merging, as this is better than the current version.

**Pull request merged**
