### PR TITLE
Add Heave to environment.json

### PR DESCRIPTION
**Pull request by sumps**
Although it was not in my list of PGNs to be supported by iKommunicate V1, I know that some of you have been playing with 9 axis sensors and so perhaps it would be useful to have Heave included in SK. Basically negative measurement value means you are moving up on a wave and positive value means you are going down in to the trough of a wave.

### CODE REVIEW

**Comment by rob42** [comment]
Merged into beta1

**Comment by tkurki** [comment]
Should this be under `navigation` like attitude (roll, pitch, yaw) is?

**Comment by sumps** [comment]
No Heave is effectively sea state and that is very much environment, although after the Time/Date discussions, I am no longer clear on what the scope of these two groups are ;-)

**Comment by tkurki** [comment]
Makes sense. Attitude is boat, heave is sea.

**Pull request merged**
