### PR TITLE
Convert docs to use verified json samples

### PR DESCRIPTION
**Pull request by bkp7**
I have implemented the changes required to achieve inserting validated json into md files as part of the publish process per #417.

Docs modified to include links to new sample files containing validated json.

Docs are updated as part of the docs production in docs:prep

I've also checked that the format of the links used is compatible with npm, GitHub and Gitbook docs. I have produced all the documentation to check the pdf production is OK.

### CODE REVIEW

**Comment by tkurki** [comment]
If I rebase this on master and do `npm run docs:prep && npm run docs:serve` I end up with

image

**Comment by bkp7** [comment]
Sorry, my mistake, the version insert part of the docs:prep script isn't cross platform due to (replace _version_ $npm_package_version gitbook-docs/*) and I messed it up. Reverted now. Tested docs:prep script on Linux and all OK now.

**Comment by tkurki** [comment]
Could you please rebase on master & fix?

**Comment by bkp7** [comment]
Rebased on master, fixed and flattened.

**Comment by tkurki** [comment]
This is really cool, thank you! The next level would be to generate the samples with real software, then validate, then include like this in the docs.

**Pull request merged**
