### PR TITLE
Fix: reducedState as object

### LINKED ISSUE #525: sails.json
Hey,

in sails.json (https://github.com/SignalK/specification/blob/master/schemas/groups/sails.json) on line 63, 64 there is the definition for reducedStat. 

` "reducedState": {
              "properties": {
                "reduced": {
                  "type": "boolean",`

I think `"type": "object"` is missing before properties.

Best,
Martin

### PR DESCRIPTION
**Pull request by joabakk**
fixes #525

### CODE REVIEW

**Comment by joabakk** [comment]
I would be happy to, when time permits. Rather surprisingly, the test never failed. Any idea how to make a test that is more general than just checking if this specific one is an object?

**Comment by tkurki** [comment]
Which test never failed?

**Comment by joabakk** [comment]
This one: https://github.com/SignalK/specification/blob/master/test/data/vessel-valid/sails-sample.json
I'm just trying to figure out what to test for. First of all, should all paths in the tree have a description and a type? I don't want the tests to be too specific for one PR

**Comment by tkurki** [comment]
See https://github.com/heiamoss/specification/pull/1 for adding a test that detects if the schema detects invalid reduced state.

**Comment by joabakk** [comment]
Thanks @tkurki you did it for me again. That was not my intention. Now how do we get travis to look at this again?

**Pull request merged**
