### PR TITLE
Added timezoneRegion to environment.time

### PR DESCRIPTION
**Pull request by bkp7**
This allows the timezone to be defined as a region and thus allow for daylight saving as is commonplace in other systems. Also added tests for the new key.  Deals with issue #322.

### CODE REVIEW

**Comment by rob42** [comment]
I dont follow why we need the time zone region?
We store the dateTime in UTC, isnt the timezone a local UI specific decision?

**Comment by bkp7** [comment]
@rob42, yes arguably it is......

However, we have been working on setting up many displays on board (basically replacing all fixed displays and MFDs etc with SignalK displays at 2 helm positions and other locations too) and setting the time zone for each is a real pain. This is designed so that when the vessel moves to a new time zone it can be set once on a server and then picked up by each display. There is no reason the UI would be obliged to use the server supplied time zone, nor is supplying the timezone mandatory for the server.

**Comment by bkp7** [comment]
@rob42, sorry my last comment was misleading, I should have read my own notes again before commenting from memory. This was highlighted when we had multiple displays and wondered whether they would update for Daylight saving time.

There is already an existing a timezone property which supports an offset set in the server which then flows out to each display. A timezone eg. London could be set within the server (but outside the SK design) and the server could insert the correct offset in hours:mins depending on the time of year, which would allow for Daylight saving.

However the display/end user doesn't know whether the server has a fixed offset which will go wrong with DST, or whether a zone has been set which will vary the offset according to the time of year. If a display shows '12:05 (UTC+01:00)' I would not expect that to deal with DST, ie it's a fixed offset, but if a display shows '12:05 (Europe/London)' I would expect it to automatically take care of DST.

So, this change adds the optional timezoneRegion which the UI can display. Note that timezone must be present if timezoneRegion is present.

I have updated the description to provide more clarity.

Your point about naming the timezone as onboardTimezone, I think is a good one, but I have not changed that yet as both the existing 'timezone' and my proposed 'timezoneRegion' would logically become 'onboardTimezone' and 'onboardTimezoneRegion'. I'm reluctant to rename an existing property???

If we do decide to rename the existing property I think that 'onboardTimezoneOffset' and onboardTimezoneRegion' might be better choices.

**Comment by rob42** [comment]
Actually I have another idea. Change `timezone` to `timezoneOffset` for clarity. If we leave the out 'onboard' bit out its more generic, and we can later re-use the time object in other trees, like `aircraft` and `fixed`.

**Comment by bkp7** [comment]
Agreed and done.

Also slightly changed wording in description to say 'on vessel' rather than 'onboard', at least to be consistent with current 'vessel' use elsewhere.

**Comment by bkp7** [comment]
Oops, finger trouble, sorry.

**Comment by rob42** [comment]
Can you close this pls, no button for me

**Pull request merged**
